// server/models/PendingAIResponse.js
const mongoose = require("mongoose");

const PendingAIResponseSchema = new mongoose.Schema(
  {
    expertSystemID: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ExpertSystem",
      required: true,
      index: true
    },

    // Source tracking
    source: {
      type: String,
      enum: ["business_profile", "ollama", "manual"],
      default: "business_profile"
    },

    // UI Grouping & Category Alignment
    category: {
      type: String,
      enum: [
        "general",
        "product",
        "service",
        "pricing",
        "policy",
        "objection",
        "lead_qualification",
        "upsell",
        "greeting",
        "closing"
      ],
      default: "general"
    },

    // --- core FAQ fields (mirrors FAQ schema) ---
    intent: {
      type: String,
      required: true,
      trim: true
    },

    primaryQuestion: {
      type: String,
      required: true,
      trim: true
    },

    normalizedQuestion: {
      type: String,
      required: true,
      trim: true
    },

    questionEmbedding: {
      type: [Number],
      default: []
    },

    // Array of alternative questions generated by AI
    variations: [
      {
        text: { type: String, required: true },
        normalizedText: { type: String, required: true },
        embedding: { type: [Number], default: [] }
      }
    ],

    primaryResponse: {
      type: String,
      required: true,
      trim: true
    },

    // Keywords/Tags for keyword-matching pipeline
    keywords: {
      type: [String],
      default: []
    },

    // Metadata matching FAQ schema requirements
    metadata: {
      language: { type: String, default: "en" },
      tone: { type: String, default: "Professional" },
      autoGenerated: { type: Boolean, default: true }
    },

    // --- Approval Workflow Controls ---
    confidence: {
      type: Number,
      default: 85
    },

    reasoning: {
      type: String,
      default: "Generated from Business Profile details."
    },

    status: {
      type: String,
      enum: ["pending", "approved", "edited", "rejected"],
      default: "pending",
      index: true
    },

    reviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null
    }
  },
  { timestamps: true }
);

PendingAIResponseSchema.index({ expertSystemID: 1, status: 1 });

module.exports = mongoose.model("PendingAIResponse", PendingAIResponseSchema);